import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.JS - Tutorial - Shiroe",
    template: "%s | Shiroe",
  },
  description: "Generate By Next JS "
}


// export const metadata = {
//   title: 'Next JS Study Project',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
        style={{
          backgroundColor: "lightBlue",
          padding: "1rem",
        }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "gray",
            padding: "1rem",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
